spring.application.name=KinoPoiskZ

spring.datasource.url=jdbc:postgresql://localhost:5432/kinopoisk
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.config.import=optional:classpath:application-local.properties